changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableGlobalCache: false

nmHoistingLimits: workspaces

packageExtensions:
  '@cypress/webpack-dev-server@*':
    dependencies:
      lodash: '*'
  '@mdx-js/loader@*':
    dependencies:
      react: '*'
  '@types/hoist-non-react-statics@*':
    dependencies:
      react: '*'
  '@types/mdx-js__react@*':
    dependencies:
      react: '*'
  '@types/react-dom@*':
    dependencies:
      react: '*'
  '@types/react-router-dom@*':
    dependencies:
      react: '*'
  '@types/react-router@*':
    dependencies:
      react: '*'
  '@types/react-transition-group@*':
    dependencies:
      react: '*'
  '@types/styled-components@*':
    dependencies:
      react: '*'
  babel-plugin-styled-components@*:
    dependencies:
      react: '*'
      react-dom: '*'
      react-is: '*'
      styled-components: '*'
  cypress@*:
    dependencies:
      graceful-fs: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-config-typescript-shareable@*:
    dependencies:
      stylelint: '*'
      stylelint-config-recommended: '*'
      stylelint-config-styled-components: '*'
      stylelint-processor-styled-components: '*'
  eslint-module-utils@*:
    dependencies:
      eslint: '*'
      eslint-import-resolver-node: '*'
  focus-trap-react@*:
    dependencies:
      '@types/react': '*'
  formik@*:
    dependencies:
      '@types/react': '*'
  jest-styled-components@*:
    dependencies:
      react: '*'
      react-dom: '*'
      react-is: '*'
      styled-components: '*'
  license-webpack-plugin@*:
    dependencies:
      webpack: '*'
  practical-react-components-formik@*:
    dependencies:
      pepjs: '*'
  react-live@*:
    dependencies:
      react: '*'
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
